[package]
name = "rename_me"
version = "0.1.0"
edition = "2021"


[dependencies]
cranelift = "0.109.0"
lazy_static = "1.4.0"
lexical = { version = "6.1.1", features = ["power-of-two", "format"] }
pest = "2.7.11"
pest_derive = "2.7.11"
